apiVersion: apps/v1
kind: Deployment

metadata:
  name: skyforge-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: skyforge-frontend:v1

        imagePullPolicy: Never

        ports:
        - containerPort: 5173


        