pipeline {
    agent any

    stages {

        stage('Verify Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Verify Backend Dockerfile') {
            steps {
                sh 'ls docker/backend'
            }
        }

        stage('Verify Frontend Dockerfile') {
            steps {
                sh 'ls docker/frontend'
            }
        }

        stage('Pipeline Success') {
            steps {
                echo 'SkyForge CI Pipeline Executed Successfully'
            }
        }
    }
}