pipeline {
    agent any

    stages {

        stage('Verify Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Verify Backend Dockerfile') {
            steps {
                sh 'ls docker/backend'
            }
        }

        stage('Verify Frontend Dockerfile') {
            steps {
                sh 'ls docker/frontend'
            }
        }

        stage('Pipeline Success') {
            steps {
                echo 'SkyForge CI Pipeline Executed Successfully'
            }
        }
        stage('Deploy to Kubernetes') {
    steps {
        sh 'kubectl apply -f kubernetes/backend/backend-deployment.yaml'
        sh 'kubectl apply -f kubernetes/backend/backend-service.yaml'
        sh 'kubectl apply -f kubernetes/frontend/frontend-deployment.yaml'
        sh 'kubectl apply -f kubernetes/frontend/frontend-service.yaml'
    }
}
    }
}
