pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/sanchitaaa10/skyforge-devops.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t skyforge-backend:v1 -f docker/backend/Dockerfile .'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t skyforge-frontend:v1 -f docker/frontend/Dockerfile .'
            }
        }

        stage('Verify Images') {
            steps {
                sh 'docker images'
            }
        }
    }
}